In [3]:
import pandas as pd

# Caricamento del dataset dell'espressione genica
expression_data_path = '../data/COAD_mutation.csv'
expression_data = pd.read_csv(expression_data_path, sep = ";")

# Visualizzazione delle prime righe del dataset per comprenderne la struttura
expression_data.head()

,GENE,TCGA-AA-A00N-01A-02D-A17O-10,TCGA-AA-A00N-01A-02W-A00E-09,TCGA-AM-5821-01A-01D-1650-10,TCGA-AZ-4315-01A-01D-1408-10,TCGA-CA-6717-01A-11D-1835-10,TCGA-CM-6677-01A-11D-1835-10,TCGA-D5-6531-01A-11D-1719-10,TCGA-D5-6540-01A-11D-1719-10,TCGA-A6-2686-01A-01D-1408-10,...,TCGA-A6-2678-01A-01D-1953-10,TCGA-AA-3812-01A-01W-0900-09,TCGA-A6-2674-01A-02D-1953-10,TCGA-AA-3532-01A-01D-1953-10,TCGA-AA-3531-01A-01D-1953-10,TCGA-AA-3561-01A-01D-1953-10,TCGA-AA-3521-01A-01D-1953-10,TCGA-AA-3524-01A-02D-1953-10,TCGA-AA-3534-01A-01D-1953-10,TCGA-AA-3517-01A-01D-1953-10
0,A1BG,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,A1CF,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,A2M,2,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,A2ML1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,A3GALT2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0